# Generated by Django 3.2.4 on 2021-07-10 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_alter_book_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='category',
            field=models.CharField(choices=[('Action', 'Action'), ('Romance', 'Romance'), ('Horror', 'Horror'), ('Comedy', 'Comedy'), ('Adventure', 'Adventure'), ('Dramatic', 'Dramatic')], default='Undefined', max_length=20),
        ),
    ]
