# Generated by Django 3.2.4 on 2021-07-13 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0004_auto_20210711_1335'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='book',
            options={'ordering': ['price']},
        ),
        migrations.AlterField(
            model_name='book',
            name='category',
            field=models.CharField(choices=[('Action', 'Action'), ('Romance', 'Romance'), ('Horror', 'Horror'), ('Comedy', 'Comedy'), ('Adventure', 'Adventure'), ('Dramatic', 'Dramatic'), ('Crime', 'Crime')], max_length=20),
        ),
        migrations.AlterField(
            model_name='book',
            name='image',
            field=models.ImageField(blank=True, upload_to='photos/%y/%m/%d'),
        ),
    ]
