# Generated by Django 3.2.4 on 2021-07-16 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0006_book_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='ISBN',
            field=models.CharField(max_length=13, null=True),
        ),
        migrations.AddField(
            model_name='book',
            name='publication_year',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='book',
            name='author',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='book',
            name='category',
            field=models.CharField(choices=[('Action', 'Action'), ('Romance', 'Romance'), ('Horror', 'Horror'), ('Comedy', 'Comedy'), ('Adventure', 'Adventure'), ('Dramatic', 'Dramatic'), ('Crime', 'Crime'), ('Fantasy', 'Fantasy')], max_length=20),
        ),
    ]
