# Generated by Django 3.2.4 on 2021-07-16 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0008_alter_book_publication_year'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='publication_year',
            field=models.CharField(max_length=4, null=True),
        ),
    ]
