# Generated by Django 3.2.4 on 2021-07-18 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0017_auto_20210718_1020'),
    ]

    operations = [
        migrations.AddField(
            model_name='borrow',
            name='period',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
