# Generated by Django 3.2.4 on 2021-07-18 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0018_borrow_period'),
    ]

    operations = [
        migrations.AlterField(
            model_name='borrow',
            name='id',
            field=models.PositiveIntegerField(primary_key=True, serialize=False),
        ),
    ]
